name: CI Prueba Unitaria

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos de ejecución a jest
        run: chmod +x node_modules/.bin/jest

      - name: Ejecutar pruebas
        run: npm test
